version: "3.0"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - cmak
  kafka:
    image: 'bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    expose:
      - '9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - cmak
  cmak:
    image: 'srvz/cmak:3.0.0.5'
    ports:
      - '9000:9000'
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - kafka
    networks:
      - cmak

networks:
  cmak:
    driver: bridge