name: Build base image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of cmak'
        required: true
        default: '3.0.0.5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login https://docker.pkg.github.com -u srvz -p ${{ secrets.GITHUB_TOKEN }}
    - name: build base image
      env:
        image: 'docker.pkg.github.com/srvz/cmak/cmak:base'
        version: ${{ github.event.inputs.version }}
      run: |
        cd base
        docker build -f Base --build-arg "VERSION=${version}" -t ${image} .
        docker push ${image}