name: Build release image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of cmak'
        required: true
        default: '3.0.0.5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u srvz -p ${{ secrets.DOCKER_TOKEN }}
    - name: Build image
      env:
        image: 'srvz/cmak:${{ github.event.inputs.version }}'
        version: ${{ github.event.inputs.version }}
      run: |
        docker build --build-arg "VERSION=${version}" -t ${image} .
        docker push ${image}
        docker tag ${image} srvz/cmak:latest
        docker push srvz/cmak:latest